name: $(Build.BuildId)

trigger:
 branches:
   include:
     - master

variables:
- group: 'Secrets'  # link to a variable group that has secret variables, like URL to license file, or sasToken for insider builds

pool: Default

steps:
- checkout: self
  clean: true 

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

- task: ALOpsAppCompiler@2
  inputs:
    artifacttype: 'Sandbox'
    alsourcepath: 'MainApp/app.json'
    appversiontemplate: '?.?.[yyyyWW].*'
    appfilenametemplate: '%APP_PUBLISHER%_%APP_NAME%_%APP_VERSION%.app'